import { StylesObj } from "../../StyledMUI";

export const Styles: StylesObj = {
  fatherContainerCategories: {
    width: "100%",
    display: "flex",
  },
  childContainerCategories: {
    margin: 3,
    width: "95%",
  },
  boxTitleViewCategories: {
    width: "100%",
    height: "45px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "gray",
    border: "1px solid #c6c4c9",
    color: "white",
  },
  boxChildFiltersCategories: {
    width: "100%",
    height: "100px",
    backgroundColor: "#e9e7eb",
    border: "1px solid #c2c0c4",
    display: "flex",
    flexDirection: "row",
  },
  boxFilterCategorie: {
    width: "80%",
    height: "100%",
    borderRight: "5px solid gray",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  boxNewCategorie: {
    width: "20%",
    height: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
  },
  textFieldFilterCategorie: {
    width: "20%",
    marginLeft: "1.5rem",
  },
  btnGoTitleCategorie: {
    marginTop: "2px",
    backgroundColor: "white",
    color: "black",
    marginLeft: "1.5rem",
    height: "2.3rem",
    "&:hover": {
      backgroundColor: "gray",
    },
  },
  btnResetFilterCategorie: {
    marginTop: "2px",
    backgroundColor: "white",
    color: "black",
    marginLeft: "1.5rem",
    height: "2.3rem",
    "&:hover": {
      backgroundColor: "gray",
    },
  },
  btnClearCache: {
    marginTop: "2px",
    backgroundColor: "white",
    color: "black",
    marginLeft: "1.5rem",
    height: "2.3rem",
    "&:hover": {
      backgroundColor: "gray",
    },
  },
  selectFilterContains: {
    width: "20%",
    marginLeft: "1.5rem",
  },
  // Styles to table categories
  boxTableCategories: {
    width: "100%",
    border: "1px solid #c2c0c4",
  },
  // Styles for component create/update categories
  boxFatherNewEditCategorie: {
    width: "100%",
    display: "flex",
  },
  boxCategorieCUdTitle: {
    width: "100%",
    height: "30px",
    backgroundColor: "gray",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  styledTitleViewCategorieCU: {
    color: "white",
    fontSize: 18,
    fontWeight: 500,
    width: "97%",
    textAlign: "center",
  },
  boxChildCrudCategories: {
    margin: 3,
    width: "95%",
    border: "1px solid #c2c0c4",
    backgroundColor: "#e9e7eb",
  },
  boxSubCategorieCu: {
    width: "95%",
    height: "100%",
    margin: 3,
  },
  boxSelectSubCategorieCu: {
    width: "100%",
  },
  boxSelectThumbnailCategorieIcon: {
    marginTop: "10px",
    width: "20%",
    height: "13%",
    backgroundColor: "#c2c0c4",
    borderTopRightRadius: "18px",
    borderTopLeftRadius: "18px",
    display: "flex",
    justifyContent: "end",
    alignItems: "center",
  },
  boxSelectThumbnailCategorieImage: {
    width: "20%",
    height: "87%",
    backgroundColor: "gray",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  boxLandingPageLine: {
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  boxCodeCatLandingPage: {
    width: "50%",
    height: "100%",
  },
  boxPreviewCatLandingPage: {
    width: "50%",
    height: "100%",
  },
  boxIconsLandingPage: {
    width: "100%",
    height: "22%",
    backgroundColor: "rgba(84,84,84,255)",
    borderTopRightRadius: "19px",
    borderTopLeftRadius: "19px",
  },
  boxTextCodeLandingPage: {
    width: "100%",
    height: "78%",
  },
  boxIconUpDown: {
    width: "3%",
    display: "flex",
    alignItems: "center",
    margin: "5px",
  },
  iconsUpDownPageDescription: {
    width: "100%",
    height: "50%",
    borderRadius: "30px",
    marginTop: "3rem",
    backgroundColor: "#c2c0c4",
    border: "1px solid gray",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "column",
  },
  boxTitleLandingPageMenuCollapsed: {
    width: "100%",
    height: "30px",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "gray",
    marginTop: "3rem",
  },
  rotateDown: {
    transform: "rotate(180deg)",
  },
  rotateUp: {
    transform: null,
  },
  boxPageLadingSeoOpen: {
    width: "100%",
    height: "400px",
    transition: "all 0.5s",
    overflow: "auto",
    marginTop: "10px",
  },
  boxPageLadingSeoClose: {
    width: "100%",
    height: 0,
    transition: "all 0.5s",
    overflow: "hidden",
  },
};
